name: Zip Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Read Json Properties Action
        uses: Muchaszewski/read-json-action@1.0.0
        with:
          path: "./info.json"
          properties: "name, version"

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          type: zip
          filename: "{{steps.read_property.outputs.name}}_{{steps.read_property.outputs.version}}.zip"
          exclusions: "*.git* /*.vscode/* /*.github/*"

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "{{steps.read_property.outputs.name}}_{{steps.read_property.outputs.version}}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}